const SERVICE_CATALOG = [
  {
    id: "data",
    name: "Data",
    description: "Buy data bundles across supported networks.",
    icon: "📶",
    category: "connectivity",
    route: "/buy",
    status: "available",
    serviceType: "DATA",
  },
  {
    id: "airtime",
    name: "Airtime",
    description: "Top up any supported Nigerian mobile number.",
    icon: "📞",
    category: "connectivity",
    route: "/airtime",
    status: "available",
    serviceType: "AIRTIME",
  },
  {
    id: "electricity",
    name: "Electricity",
    description: "Pay supported electricity bills.",
    icon: "⚡",
    category: "bills",
    route: "/electricity",
    status: "available",
    serviceType: "ELECTRICITY",
  },
  {
    id: "cable",
    name: "Cable TV",
    description: "Manage supported TV subscriptions.",
    icon: "📺",
    category: "bills",
    route: "/cable",
    status: "available",
    serviceType: "TV",
  },
  {
    id: "exam-pins",
    name: "Exam Pins",
    description: "Purchase supported education result-checker pins.",
    icon: "🎓",
    category: "education",
    route: "/pins",
    status: "available",
    serviceType: "EXAM_PIN",
  },
  {
    id: "airtime-to-cash",
    name: "Airtime to Cash",
    description: "Submit an airtime-to-cash request for review.",
    icon: "🔄",
    category: "money",
    route: "/airtime-to-cash",
    status: "available",
    serviceType: "AIRTIME_TO_CASH",
  },
  {
    id: "wallet",
    name: "Wallet",
    description: "Fund and manage your NEX wallet.",
    icon: "💳",
    category: "money",
    route: "/wallet",
    status: "available",
    serviceType: "WALLET",
  },
  {
    id: "virtual-account",
    name: "Virtual Account",
    description: "Use your dedicated bank account to fund NEX.",
    icon: "🏦",
    category: "money",
    route: "/virtual-account",
    status: "available",
    serviceType: "VIRTUAL_ACCOUNT",
  },
  {
    id: "e-pin",
    name: "Digital ePINs",
    description: "Digital PIN products for supported services.",
    icon: "🎟️",
    category: "digital",
    route: null,
    status: "coming_soon",
    serviceType: "EPIN",
  },
  {
    id: "recharge-card",
    name: "Recharge Cards",
    description: "Generate supported recharge PIN products.",
    icon: "🪪",
    category: "digital",
    route: null,
    status: "coming_soon",
    serviceType: "RECHARGE_CARD",
  },
  {
    id: "esim",
    name: "eSIM",
    description: "Digital SIM connectivity products.",
    icon: "📱",
    category: "connectivity",
    route: null,
    status: "coming_soon",
    serviceType: "ESIM",
  },
  {
    id: "transfers",
    name: "Bank Transfer",
    description: "Send money from your NEX wallet to supported bank accounts.",
    icon: "💸",
    category: "money",
    route: "/transfer",
    status: "available",
    serviceType: "TRANSFER",
  },
  {
    id: "merchant",
    name: "Merchant",
    description: "Business tools for accepting and managing payments.",
    icon: "🏪",
    category: "business",
    route: null,
    status: "coming_soon",
    serviceType: "MERCHANT",
  },
  {
    id: "api",
    name: "NEX API",
    description: "Developer access to NEX services.",
    icon: "💻",
    category: "business",
    route: null,
    status: "coming_soon",
    serviceType: "API",
  },
];

function getCatalog({ includeComingSoon = true } = {}) {
  return includeComingSoon
    ? SERVICE_CATALOG
    : SERVICE_CATALOG.filter((item) => item.status === "available");
}

module.exports = { SERVICE_CATALOG, getCatalog };
